apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
    name: springboot-k8s-deployment
spec:
    selector:
        matchLabels:
            app: springboot-k8s-deployment
    replicas: 3 # Number of replicas that will be created for this deployment
    template:
        metadata:
            labels:
                app: springboot-k8s-deployment
        spec:
            containers:
                - name: springboot-k8s-deployment
                  image: kubernet:1.0 # Image that will be used to containers in the cluster
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080 # The port that the container is running on in the cluster
